# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='can_i_lend',
            new_name='allowed_to_lend',
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='books.Tag'),
        ),
    ]
